spring:
  datasource:
    url: jdbc:mysql://moviemeetme-db.mysql.database.azure.com:3306/mmm?useSSL=true
    username: mmmMaster
    password: Fakultaet73
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect